name: 中青阅读

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * * '
  watch:
    types: [started]
  repository_dispatch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
    
      - name: 'Install requirements'          
        run: pip install -r ./requirements.txt 
    
      - name: 'run 中青阅读' 
        run: python3 youth_read.py 
